/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index';
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId';
import { Route as WorkflowsNewRouteImport } from './routes/workflows/new';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any);
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any);
const WorkflowsNewRoute = WorkflowsNewRouteImport.update({
  id: '/workflows/new',
  path: '/workflows/new',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute;
  '/workflows/new': typeof WorkflowsNewRoute;
  '/workflows/': typeof WorkflowsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute;
  '/workflows/new': typeof WorkflowsNewRoute;
  '/workflows': typeof WorkflowsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute;
  '/workflows/new': typeof WorkflowsNewRoute;
  '/workflows/': typeof WorkflowsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/workflows/$workflowId' | '/workflows/new' | '/workflows/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/workflows/$workflowId' | '/workflows/new' | '/workflows';
  id:
    | '__root__'
    | '/'
    | '/workflows/$workflowId'
    | '/workflows/new'
    | '/workflows/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute;
  WorkflowsNewRoute: typeof WorkflowsNewRoute;
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workflows/': {
      id: '/workflows/';
      path: '/workflows';
      fullPath: '/workflows/';
      preLoaderRoute: typeof WorkflowsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId';
      path: '/workflows/$workflowId';
      fullPath: '/workflows/$workflowId';
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/workflows/new': {
      id: '/workflows/new';
      path: '/workflows/new';
      fullPath: '/workflows/new';
      preLoaderRoute: typeof WorkflowsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  WorkflowsNewRoute: WorkflowsNewRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
